[package]
name = "kattis_test_tools"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
curl = "0.4.38"
zip-extract = "0.1.0"

[[bin]]
path = "src/main.rs"
name = "ktt"